name: Update express_mono in express-mono-repo to lastest release
on:
    # release:
    #     # Options: published, unpublished, created, edited, deleted, prereleased
    #     types: [published]
  push:
    branches:
      - first-action
jobs:
  build:
    name: Update express-mono-upstream action
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - uses: ./action-a
      env:
        EXPRESS_VERSION: "v4.0.0"
        TOKEN: ${{ secrets.OSRWEBDEPLOY_TOKEN }}